// Auto generated by "npm run schema:gen"

let path = []
let errors = []

function pushPath(newElement) {
  path = [...path, newElement]
}

function popPath() {
  path = path.slice(0, -1)
}

function pushError(expected, value) {
  errors.push({ path, expected, value: typeof value === 'object' ? JSON.stringify(value) : value })
}

function isUnbound(x) {
  if (typeof x !== 'undefined') {
    pushError('unbound', x)
  }
}

function isString(x) {
  if (typeof x !== 'string') {
    pushError('string', x)
  }
}

function isNumber(x) {
  if (typeof x !== 'number') {
    pushError('number', x)
  }
}

function isBoolean(x) {
  if (typeof x !== 'boolean') {
    pushError('boolean', x)
  }
}

function isNull(x) {
  if (x !== null) {
    pushError('null', x)
  }
}

function isAny(x) {
  if (typeof x === 'undefined') {
    pushError('any', x)
  }
}

function isObject(x) {
  if (typeof x !== 'object' || Array.isArray(x)) {
    pushError('object', x)
  }
}

function hasSameShapeAs(subSchema) {
  return function(x) {
    return Object.keys(subSchema).forEach((schemaKey) => {
      pushPath(schemaKey)
      subSchema[schemaKey](x[schemaKey])
      popPath()
    })
  }
}

function isArrayOf(subSchema) {
  return function(x) {
    if (!Array.isArray(x)) {
      pushError('array', x)
    } else {
      x.forEach((element, index) => {
        pushPath(index)
        subSchema(element)
        popPath()
      })
    } 
  }
}

function oneOf(subSchemas) {
  return function(x) {
    const errorsBefore = [...errors]
    subSchemas.forEach((subSchema) => {
      subSchema(x, true)
    })
    const errorsCreated = errors.slice(errorsBefore.length)
    errors = errorsBefore
    if (errorsCreated.length === subSchemas.length) {
      pushError(`One of: ${subSchemas.map((schema) => {if (typeof schema === 'function') {return schema.name} else {return schema}})}`, x)
    }
  }
}

// We could validate more of this in the future.
function validateSlate(slate) {
  return !slate || Array.isArray(slate)
}

const validator = hasSameShapeAs({
  "file": hasSameShapeAs({
    "fileName": isString,
    "loaded": isBoolean,
    "dirty": isBoolean,
    "version": isString,
    "id": oneOf([isNull,isString]),
    "appliedMigrations": function (migrations) {
      migrations.forEach((migration, index) => {
        if (!migration.match(/^\*?m[0-9]{4}_[0-9][0-9]?_[0-9][0-9]?/)) {
          pushPath(index)
          pushError('Invalid migration', migration)
          popPath()
        }
      })
    },
    "initialVersion": isString,
    "isCloudFile": isBoolean,
    "versionStamp": isString,
  }),
  "ui": hasSameShapeAs({
    "currentView": isString,
    "currentTimeline": isNumber,
    "orientation": isString,
    "darkMode": isBoolean,
    "characterSort": isString,
    "characterFilter": hasSameShapeAs({
      "tag": isArrayOf(isNumber),
      "book": isArrayOf(isNumber),
      "category": isArrayOf(isNumber),
      "color": isArrayOf(isNumber),
    }),
    "placeSort": isString,
    "placeFilter": hasSameShapeAs({
      "tag": isArrayOf(isNumber),
      "book": isArrayOf(isNumber),
      "category": isArrayOf(isNumber),
      "color": isArrayOf(isNumber),
    }),
    "noteSort": isString,
    "noteFilter": hasSameShapeAs({
      "tag": isArrayOf(isNumber),
      "book": isArrayOf(isNumber),
      "category": isArrayOf(isNumber),
      "color": isArrayOf(isNumber),
      "place": isArrayOf(isNumber),
      "character": isArrayOf(isNumber),
    }),
    "timelineIsExpanded": isBoolean,
    "timelineFilter": hasSameShapeAs({
      "tag": isArrayOf(isNumber),
      "character": isArrayOf(isNumber),
      "place": isArrayOf(isNumber),
    }),
    "outlineFilter": isObject,
    "timelineScrollPosition": hasSameShapeAs({
      "x": isNumber,
      "y": isNumber,
    }),
    "timeline": hasSameShapeAs({
      "size": isString,
      "view": isString,
    }),
    "searchTerms": hasSameShapeAs({
      "notes": oneOf([isString,isNull]),
      "characters": oneOf([isString,isNull]),
      "places": oneOf([isString,isNull]),
      "tags": oneOf([isString,isNull]),
      "outline": oneOf([isString,isNull]),
      "timeline": oneOf([isString,isNull]),
    }),
    "attributeTabs": hasSameShapeAs({
      "characters": isNumber,
    }),
    "characterTab": hasSameShapeAs({
      "selectedCharacter": isNull,
    }),
    "customAttributeOrder": hasSameShapeAs({
      "characters": isArrayOf(hasSameShapeAs({
        "type": isString,
        "id": isNumber,
      })),
    }),
    "cardDialog": hasSameShapeAs({
      "cardId": isNull,
      "lineId": isNull,
      "beatId": isNull,
      "isOpen": isBoolean,
    }),
    "collaborators": isObject,
    "bookDialog": hasSameShapeAs({
      "bookId": isNull,
      "isOpen": isBoolean,
    }),
    "outlineScrollPosition": isNumber,
    "templateModal": hasSameShapeAs({
      "expanded": isBoolean,
    }),
    "actConfigModal": hasSameShapeAs({
      "open": isBoolean,
    }),
    "resturctureTimelineModal": hasSameShapeAs({
      "open": isBoolean,
    }),
    "attributesDialogIsOpen": isBoolean,
  }),
  "featureFlags": isObject,
  "series": hasSameShapeAs({
    "name": isString,
    "premise": isString,
    "genre": isString,
    "theme": isString,
    "templates": isArrayOf(isAny),
  }),
  "books": function(books) {
    const bookKeys = Object.keys(books).filter((key) => {
      return key !== 'allIds'
    })
    bookKeys.every((key) => {
      try {
        if (`${parseInt(key)}` !== key) {
          pushPath(key)
          pushError('number', key)
          popPath()
        }
      } catch (error) {
        pushPath(key)
        pushError('number', key)
        popPath()
      }
    })
    const isValidBook = (book) => {
      hasSameShapeAs({
    "id": isNumber,
    "title": isString,
    "premise": isString,
    "genre": isString,
    "theme": isString,
    "templates": isArrayOf(isAny),
    "imageId": oneOf([isNull,isString]),
    "timelineTemplates": isArrayOf(oneOf([isAny,isString])),
  })(book)
    }
    bookKeys.forEach((next) => {
      pushPath(next)
      isValidBook(books[next])
      popPath()
    })
    if (!Array.isArray(books.allIds) || !books.allIds.every((id) => {
      return typeof id === 'number'
    })) {
      pushPath('allIds')
      pushError('array of numbers', books.allIds)
      popPath()
    }
  },
  "beats": function (beats) {
        if (typeof beats.series === 'undefined') {
          pushError('object', beats.series)
        }
      const nonSeriesKeys = Object.keys(beats).filter((key) => {
        return key !== 'series'
      })
      nonSeriesKeys.forEach((key) => {
      try {
        if (`${parseInt(key)}` !== key) {
          pushPath(key)
          pushError('number', key)
          popPath()
        }
      } catch (error) {
        pushPath(key)
        pushError('number', key)
        popPath()
      }
    })
      // We could also consider verifying the relationships between
      // beats, but this is good enough for now.
      const validateTree = (tree) => {
        pushPath('index')
        Object.values(tree.index).forEach((beat) => {
          pushPath(beat.id)
          hasSameShapeAs({
    "id": isNumber,
    "bookId": oneOf([isNumber,isString]),
    "position": isNumber,
    "title": isString,
    "time": isNumber,
    "templates": oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([isArrayOf(isAny),isUnbound]),isUnbound]),isUnbound]),isUnbound,isArrayOf(isAny)]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound,isArrayOf(isAny)]),
    "autoOutlineSort": isBoolean,
    "fromTemplateId": oneOf([oneOf([isNull,isString]),isUnbound]),
    "expanded": oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([oneOf([isBoolean,isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound,isBoolean]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound]),isUnbound,isBoolean]),
  })(beat)
          popPath()
        })
        popPath()
        pushPath('children')
        Object.keys(tree.children).forEach((id) => {
          if (id !== 'null' && typeof tree.index[id] === 'undefined') {
            pushPath(id)
            pushError('Missing children entry', tree.index[id])
            popPath()
          }
        })
        popPath()
        pushPath('heap')
        Object.keys(tree.heap).forEach((id) => {
          if (id !== 'null' && typeof tree.index[id] === 'undefined') {
            pushPath(id)
            pushError('Missing heap entry', tree.index[id])
            popPath()
          }
        })
        popPath()
        pushPath('index')
        Object.keys(tree.index).forEach((id) => {
          if (typeof tree.children[id] === 'undefined' || typeof tree.heap[id] === 'undefined') {
            pushPath(id)
            pushError('Orphan index beat')
            popPath()
          }
        })
        popPath()
      }
      ['series', ...nonSeriesKeys].forEach((next) => {
        pushPath(next)
        validateTree(beats[next])
        popPath()
      })
    },
  "cards": isArrayOf(hasSameShapeAs({
    "id": isNumber,
    "lineId": isNumber,
    "beatId": isNumber,
    "seriesLineId": oneOf([isNull,isUnbound]),
    "bookId": isNull,
    "position": oneOf([isNumber,isUnbound]),
    "title": isString,
    "description": validateSlate,
    "tags": isArrayOf(oneOf([isNumber,isAny])),
    "characters": isArrayOf(oneOf([isNumber,isAny])),
    "places": isArrayOf(oneOf([isNumber,isAny])),
    "templates": isArrayOf(isAny),
    "imageId": isNull,
    "positionWithinLine": isNumber,
    "positionInChapter": oneOf([isNumber,isUnbound]),
    "fromTemplateId": oneOf([isNull,isString]),
    "color": oneOf([isString,isUnbound,isNull]),
    "positionInBeat": oneOf([isNumber,isUnbound]),
  })),
  "categories": hasSameShapeAs({
    "characters": isArrayOf(hasSameShapeAs({
      "id": isNumber,
      "name": isString,
      "position": isNumber,
      "type": isString,
    })),
    "places": isArrayOf(isAny),
    "notes": isArrayOf(hasSameShapeAs({
      "id": isNumber,
      "name": isString,
      "position": isNumber,
      "type": isString,
    })),
    "tags": isArrayOf(hasSameShapeAs({
      "id": isNumber,
      "name": isString,
      "position": isNumber,
      "type": isString,
    })),
  }),
  "characters": isArrayOf(hasSameShapeAs({
    "id": isNumber,
    "name": isString,
    "description": isString,
    "notes": validateSlate,
    "color": isNull,
    "cards": isArrayOf(isNumber),
    "noteIds": isArrayOf(oneOf([isNumber,isAny])),
    "templates": isArrayOf(oneOf([isAny,hasSameShapeAs({
      "id": isString,
      "version": isString,
      "attributes": isArrayOf(hasSameShapeAs({
        "name": isString,
        "type": isString,
      })),
      "value": isString,
      "values": isArrayOf(hasSameShapeAs({
        "name": isString,
        "value": validateSlate,
        "bookId": isNumber,
      })),
    })])),
    "tags": isArrayOf(isNumber),
    "categoryId": isString,
    "imageId": oneOf([isString,isNull]),
    "bookIds": isArrayOf(oneOf([isNumber,isAny,isString])),
    "attributes": isArrayOf(hasSameShapeAs({
      "value": validateSlate,
      "id": isNumber,
      "bookId": isNumber,
    })),
  })),
  "customAttributes": hasSameShapeAs({
    "characters": isArrayOf(isAny),
    "places": isArrayOf(hasSameShapeAs({
      "name": isString,
      "type": isString,
    })),
    "scenes": isArrayOf(hasSameShapeAs({
      "name": isString,
      "type": isString,
    })),
    "lines": isArrayOf(isAny),
    "notes": isArrayOf(hasSameShapeAs({
      "name": isString,
      "type": isString,
    })),
  }),
  "attributes": hasSameShapeAs({
    "characters": isArrayOf(hasSameShapeAs({
      "name": isString,
      "type": isString,
      "id": isNumber,
    })),
  }),
  "lines": isArrayOf(hasSameShapeAs({
    "id": isNumber,
    "bookId": oneOf([isNumber,isString]),
    "color": isString,
    "title": isString,
    "position": isNumber,
    "characterId": oneOf([oneOf([isNull,isUnbound]),isUnbound]),
    "expanded": isNull,
    "fromTemplateId": oneOf([isNull,isString]),
    "isPinned": oneOf([oneOf([oneOf([oneOf([isBoolean,isUnbound]),isUnbound,isBoolean]),isUnbound]),isUnbound]),
  })),
  "notes": isArrayOf(hasSameShapeAs({
    "id": isNumber,
    "title": isString,
    "content": validateSlate,
    "tags": isArrayOf(isNumber),
    "characters": isArrayOf(isNumber),
    "places": isArrayOf(isNumber),
    "lastEdited": isNumber,
    "templates": isArrayOf(isAny),
    "imageId": isString,
    "bookIds": isArrayOf(oneOf([isNumber,isAny])),
    "categoryId": oneOf([oneOf([isString,isUnbound]),isUnbound]),
  })),
  "places": isArrayOf(hasSameShapeAs({
    "id": isNumber,
    "name": isString,
    "description": isString,
    "notes": validateSlate,
    "color": isNull,
    "cards": isArrayOf(oneOf([isNumber,isAny])),
    "noteIds": isArrayOf(oneOf([isNumber,isAny])),
    "templates": isArrayOf(isAny),
    "tags": isArrayOf(oneOf([isNumber,isAny])),
    "imageId": isString,
    "bookIds": isArrayOf(isNumber),
  })),
  "tags": isArrayOf(hasSameShapeAs({
    "id": isNumber,
    "title": isString,
    "color": isString,
    "categoryId": oneOf([isNumber,isUnbound]),
  })),
  "hierarchyLevels": function (hierarchyLevels) {
      if (typeof hierarchyLevels.series === 'undefined') {
        pushError('series is missing', hierarchyLevels.series)
      }
      const topLevelNonSeriesKeys = Object.keys(hierarchyLevels).filter((key) => {
        return key !== 'series'
      })
      topLevelNonSeriesKeys.every((key) => {
      try {
        if (`${parseInt(key)}` !== key) {
          pushPath(key)
          pushError('number', key)
          popPath()
        } 
      } catch (error) {
        pushPath(key)
        pushError('number', key)
        popPath()
      }
    })
      const isValidHierarchyLevelsConfig = (keyAndHierarchyLevels) => {
        const [key, hierarchyLevels] = keyAndHierarchyLevels
        pushPath(key)
        if (Object.keys(hierarchyLevels).length >= 4 || Object.keys(hierarchyLevels).length === 0) {
          pushError('Invalid number of hierarchy levels', Object.keys(hierarchyLevels).length)
        }
        Object.keys(hierarchyLevels).map((key) => {
          try {
            return parseInt(key)
          } catch (_error) {
            return -1
          }
        }).forEach((key) => {
          if (key < 0 || key > 2) {
            pushError('Invalid hierarchy level key', key)
          }
        })
        Object.entries(hierarchyLevels).every((keyAndLevel) => {
          const [key, level] = keyAndLevel
          pushPath(key)
          hasSameShapeAs({
    "name": isString,
    "level": isNumber,
    "autoNumber": isBoolean,
    "textSize": isNumber,
    "borderStyle": isString,
    "backgroundColor": isString,
    "textColor": isString,
    "borderColor": isString,
    "dark": hasSameShapeAs({
      "borderColor": isString,
      "textColor": isString,
    }),
    "light": hasSameShapeAs({
      "borderColor": isString,
      "textColor": isString,
    }),
  })(level)
          popPath()
        })
        popPath()
      }
      Object.entries(hierarchyLevels).forEach(isValidHierarchyLevelsConfig)
      popPath()
    },
  "images": function (images) {
      Object.keys(images).every((key) => {
        try {
          if (`${parseInt(key)}` !== key) {
            pushPath(key)
            pushError('number', key)
            popPath()
          }
        } catch (_error) {
          pushPath(key)
          pushError('number', key)
          popPath()
        }
      })
      Object.entries(images).forEach((keyAndImage) => {
        const [key, image] = keyAndImage
        pushPath(key)
        hasSameShapeAs({
    "id": isNumber,
    "name": isString,
    "path": isString,
    "data": isString,
  })(image)
        popPath()
      })
    },
})

export const schema = (file) => {
  errors = []
  path = []
  validator(file)
  return errors
}