osx_image: xcode7.3
os: osx
language: node_js
node_js:
  - "7"
env:
  - BUILD_TYPE=full ELECTRON_CACHE=$HOME/.electron
  - BUILD_TYPE=trial ELECTRON_CACHE=$HOME/.electron
cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache
script:
  - npm run dist
branches:
  only:
    - master
