version: 1.2.{build}
image: Visual Studio 2017
platform:
  - x64
cache:
  - node_modules
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 10 x64
  - npm install
build_script:
  - ps: set NODE_ENV=production
  - npm run dist:windows
test: off
branches:
  only:
    - master
    - beforeStickyTable
environment:
  matrix:
    - rando: anotherthing
      BUILD_TYPE: trial

    - rando: onething
      BUILD_TYPE: full
