version: 1.2.{build}
platform:
  - x64
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 7 x64
  - npm install
build_script:
  - ps: set NODE_ENV=production
  - npm run dist:windows
test: off
branches:
  only:
    - master
environment:
  matrix:
    - rando: onething
      BUILD_TYPE: full

    - rando: anotherthing
      BUILD_TYPE: trial
