version: 1.2.{build}
platform:
  - x64
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 7 x64
  - npm install
build_script:
  - ps: set NODE_ENV=production
  - npm run dist:windows
test: off
matrix:
  - BUILD_TYPE: full
  - BUILD_TYPE: trial
branches:
  only:
    - master
# environment:
#   BUILD_TYPE: full
  # matrix:
  #   - BUILD_TYPE: full
  #   - BUILD_TYPE: trial
