* Patch Release v2023.10.27

** API Changes

 - Delete Pro Backups.  *To test (Pro only):* can we delete pro backups?  A new
   delete icon appears next to each cloud backup to enable users to
   delete them.
 - API updates to authentication.  *To test (Pro only):*
   - Can we log in?
   - Can we rename a file?
   - Can we delete a file?
   - Can we share a file?
   - Does the list of Pro backups populate and update as it changes?
   - Do pro files still backup?
   - Can we save templates?
   - Can we load/use user templates?
   - Can we delete a custom template?
   - Can we upload files with images in them?
   - Can we upload images to existing files?
   - Can we download files with images in them?

** Scrivener Exporter

 - Scrivener exporter now exports a card's ~characters~, ~places~ and
   ~tags~.  It a note's ~tags~, ~characters~, ~places~ and ~category~.  It
   exports a place's ~notes~, ~tags~ and ~category~.
 - We changed the way the internals of the exporter export custom
   attributes and template attributes.
 - *To test:* does the exporter honour user choices in advanced export?
 - *To test:* does a card's ~description~, custom attributes, base
   attributes & template attributes get exported correctly.

** Scrivener Importer

 - Scrivener importer was overhauled from the ground up.  *To test:*
   regression test all known scrivener importer features.
 - Scrivener importer handles files with images in them gracefully.
   *To test:* can we import Scrivener files with images in them.
 - Scrivener importer imports bulleted lists from scrivener files.  *To
   test:* can we import a file with bullet points in it to Plottr
   bullet points.  (Limitations: it's not guaranteed to import the
   correct depth nor type of bullet.)
 - Scrivener importer should be much faster than before.  *To test:*
   find a very large scrivener file and attempt to import it.  In the
   old version it took so long that Plottr started to time out other
   requests and present the user with errors.
 - Scrivener importer is better at reading base and custom attributes.
   *To test:* can you import attributes from a Scrivener file and have
   them end up in the correct place in the Plottr file.
   (i.e. description etc. should still remain in description, but the
   custom attributes should be correctly created.).
 - Scrivener importer can now import into the Act Structure.  *To test:*
   can you create a scrivener file with binders inside of binders and
   import it into a corresponding act structure with the appropriate
   depth in Plottr?
 - Scrivener importer is robust to minor insertion spelling mistakes
   in attribute names.  i.e. you may insert/add a single letter to a
   word and it will still match it to a known attribute.
   e.g. "description" is matched when the user typed "descripstion".
   This mechanism doesn't work for missing letters.  *To test:* when
   importing a Scrivener file, can you misspell base attributes and
   still read them into notes, characters, places and cards correctly?
 - Scrivener importer correctly imports categories for entities that
   can be categorised.  *To test:* can we import characters, notes
   etc. with categories on them and have Plottr correctly categorise
   them?

** Disabled Features

 - Drag and drop (disabled).  *To test:* there should be no visible or
   behavioural changes to the list of Characters, Places or Notes on
   the left of those tabs.

** Technical Changes

 - Improved error reporting.  *To test:* (for Ed): whether we get the app
   to log errors to Rollbar in the new version.
