name: Validate

on:
  push:
    branches:
      - staging
      - prod
  pull_request:
    branches:
      - staging
      - prod

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'
      - name: Use npm 7
        run: npm i -g npm@8.8.0
      - name: Install dependencies
        run: npm ci
      - name: Install components dependencies
        run: cd lib/plottr_components && npm ci
      - name: Validation
        run: npm run validate
